name: balatro_flutter
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_shaders: ^0.1.3
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  shaders:
    - shaders/ray_marching.frag
