name: flutter_3d_ui
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_shaders: ^0.1.3
  flutter_hooks: ^0.21.2
  provider: ^6.1.2
  rename_app: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "ffffff"
  image: assets/images/wordart_title.png
  web: true
  web_image_mode: center

flutter:
  uses-material-design: true
  shaders:
    - shaders/ray_tracing.frag
  assets:
    - assets/images/
