name: flutter_3d_ui
description: "3D UI in Flutter."
publish_to: "none"

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_shaders: ^0.1.3
  flutter_hooks: ^0.21.2
  provider: ^6.1.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "AFC1D0"
  image: assets/images/wordart_title.png
  web: true
  web_image_mode: center

flutter:
  uses-material-design: true
  shaders:
    - shaders/ray_tracing.frag
  assets:
    - assets/images/
